DELETE FROM FILM_GENRES  ;
DELETE FROM FILMS  ;
ALTER TABLE FILMS  ALTER COLUMN id RESTART WITH 1;
DELETE FROM FRIENDSHIPS  ;
DELETE FROM GENRES  ;
ALTER TABLE GENRES ALTER COLUMN id RESTART WITH 1;
DELETE FROM LIKES ;
DELETE FROM RATINGS ;
ALTER TABLE RATINGS ALTER COLUMN id RESTART WITH 1;
DELETE FROM USERS  ;
ALTER TABLE USERS  ALTER COLUMN id RESTART WITH 1;

INSERT INTO ratings (name) VALUES ('G');
INSERT INTO ratings (name) VALUES ('PG');
INSERT INTO ratings (name) VALUES ('PG-13');
INSERT INTO ratings (name) VALUES ('R');
INSERT INTO ratings (name) VALUES ('NC-17');

INSERT INTO genres (name) VALUES ('Комедия');
INSERT INTO genres (name) VALUES ('Драма');
INSERT INTO genres (name) VALUES ('Мультфильм');
INSERT INTO genres (name) VALUES ('Триллер');
INSERT INTO genres (name) VALUES ('Документальный');
INSERT INTO genres (name) VALUES ('Боевик');