CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar(100) NOT NULL,
        login varchar(100) NOT NULL,
        name varchar(150),
        birthday date
);

CREATE TABLE IF NOT EXISTS friendships (
        user_id INTEGER REFERENCES users (id),
        friend_id INTEGER REFERENCES users (id),
        status BOOLEAN
);

CREATE TABLE IF NOT EXISTS ratings (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100)
);

CREATE TABLE IF NOT EXISTS films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(150),
        description varchar(500),
        release_date date,
        duration INTEGER,
        rating_id INTEGER REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS likes (
        film_id INTEGER REFERENCES films (id),
        user_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS genres (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100)
);

CREATE TABLE IF NOT EXISTS film_genres (
        film_id INTEGER REFERENCES films (id),
        genre_id INTEGER REFERENCES genres (id)
);